---
- name: Install the latest version of iotop
  hosts: web1
  become: yes
  tasks:
    - name: Update the package cache
      yum:
        name: "*"
        state: latest

    - name: Install iotop package
      yum:
        name: iotop
        state: latest
#ansible-playbook -i /home/thor/playbooks/inventory /home/thor/playbooks/iotop.yml

