---
- name: Install multiple packages on web1
  hosts: web1
  become: yes
  tasks:
    - name: Install the latest version of sudo package
      package:
        name: sudo
        state: latest

    - name: Downgrade vsftpd to version 2.2.2
      yum:
        name: vsftpd-2.2.2
        state: present
#ansible-playbook -i /home/thor/playbooks/inventory /home/thor/playbooks/multi-pkgs.yml
