---
- name: Install unzip-5.52 on web1
  hosts: web1
  become: yes
  tasks:
    - name: Install unzip-5.52 package
      yum:
        name: unzip-5.52
        state: present
#ansible-playbook -i /home/thor/playbooks/inventory /home/thor/playbooks/unzip.yml
