---
- hosts: node00.host
  gather_facts: false
  tasks:
    - name: hostinfo
      template:
        src: hostinfo.j2
        dest: /root/hostinfo

---
- name: Update and Copy Template to /root/hostinfo
  hosts: node00
  tasks:
    - name: Update the Template
      template:
        src: ~/playbooks/templates/hostinfo.j2
        dest: /root/hostinfo
      vars:
        full_inventory_hostname: "{{ inventory_hostname }}"
        short_inventory_hostname: "{{ inventory_hostname.split('.')[0] }}"
        inventory_file: "{{ inventory_file }}"
#ansible-playbook -i ~/playbooks/inventory ~/playbooks/hostinfo.yml
