---
- hosts: node00.host
  gather_facts: yes
  tasks:
    - shell: "echo  {{  }} {{ ansible_default_ipv4.address }} >> /etc/hosts"
---
- name: Add Entries to /etc/hosts
  hosts: node00.host
  tasks:
    - name: Add entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ inventory_hostname }} {{ ansible_default_ipv4.address }}"
