---
- hosts: all
  tasks:
    - name: copy a secret file to remote hosts
      copy:
        src: secret_file.txt
        dest: /root/.secret_file.txt
#ansible-playbook -i /home/thor/playbooks/inventory /home/thor/playbooks/copy_secrets.yml --vault-password-file /home/thor/playbooks/get_vault_pass.py
