#sudo vi /etc/ansible/ansible.cfg
#the change is vault_password_file = /home/thor/playbooks/vault_pass.txt
#chmod 640 /home/thor/playbooks/vault_pass.txt
#vi copy_secrets.yml
---
- hosts: all
  tasks:
    - name: copy a secret file to remote hosts
      copy:
        src: secrets_file.txt
        dest: /root/.secrets_file.txt
#ansible-playbook /home/thor/playbooks/copy_secrets.yml -i /home/thor/playbooks/inventory
