---
- name: Install, start, and enable firewalld on web1
  hosts: web1
  become: yes
  tasks:
    - name: Install firewalld package
      yum:
        name: firewalld
        state: present

    - name: Start firewalld service
      service:
        name: firewalld
        state: started

    - name: Enable firewalld service at boot
      service:
        name: firewalld
        enabled: yes
#ansible-playbook -i /home/thor/playbooks/inventory /home/thor/playbooks/firewall.yml
