---
- name: Allow HTTPS from Ansible Controller
  hosts: web1
  become: yes
  tasks:
    - name: Add firewall rule to allow HTTPS from Ansible Controller
      command: firewall-cmd --permanent --zone=internal --add-rich-rule='rule family="ipv4" source address="172.20.1.2" port protocol="tcp" port="443" accept'
      changed_when: false

    - name: Reload firewall
      command: firewall-cmd --reload
#ansible-playbook -i /home/thor/playbooks/inventory /home/thor/playbooks/https.yml
