---
- name: Download and extract master.zip from GitHub
  hosts: web1
  become: yes
  tasks:
    - name: Create directory for download
      file:
        path: /root/download
        state: directory

    - name: Download the zip archive
      get_url:
        url: https://github.com/kodekloudhub/Hello-World/archive/master.zip
        dest: /root/download/master.zip

    - name: Extract the zip archive
      unarchive:
        src: /root/download/master.zip
        dest: /root/
        remote_src: yes
      args:
        creates: /root/Hello-World-master
#ansible-playbook -i /home/thor/playbooks/inventory /home/thor/playbooks/download.yml
