---
- name: Create bz2 archive of files on web1 node
  hosts: web1
  become: yes
  tasks:
    - name: Install bzip2 package (if not already installed)
      package:
        name: bzip2
        state: present

    - name: Create bz2 archive
      command: tar -cjf /root/files.tar.bz2 /root/file1.txt /usr/local/share/file2.txt /var/log/lastlog
#ansible-playbook -i /home/thor/playbooks/inventory /home/thor/playbooks/files.yml
