---
- name: Setup Nginx and configure web content
  hosts: web1
  become: yes
  tasks:
    - name: Install Nginx package
      yum:
        name: nginx
        state: present
      register: nginx_install

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      when: nginx_install.changed

    - name: Extract nginx.zip archive
      unarchive:
        src: /root/nginx.zip
        dest: /usr/share/nginx/html/
        remote_src: yes

    - name: Replace line in index.html
      replace:
        path: /usr/share/nginx/html/index.html
        regexp: "This is sample html code"
        replace: "This is KodeKloud Ansible lab by VICTOR BOURMAN"

    - name: Display the contents of the modified file
      shell: cat /usr/share/nginx/html/index.html
      register: modified_file_content

    - name: Debug modified file content
      debug:
        var: modified_file_content.stdout_lines
#ansible-playbook -i /home/thor/playbooks/inventory /home/thor/playbooks/nginx.yml
#ssh root@172.20.1.100
#cd /usr/share/nginx/html/
#cat index.html
#Adding image of this

