---
- name: Create a zip archive of /opt directory on web1 node
  hosts: web1
  become: yes
  tasks:
    - name: Create a zip archive of /opt
      archive:
        path: /opt
        dest: /root/opt.zip
#ansible-playbook -i /home/thor/playbooks/inventory /home/thor/playbooks/zip.yml
