---
- name: Add content to index.html on web1 node
  hosts: web1
  become: yes
  tasks:
    - name: Set user and group owner for the file
      file:
        path: /var/www/html/index.html
        owner: apache
        group: apache

    - name: Add content to index.html at the beginning
      blockinfile:
        path: /var/www/html/index.html
        block: |
          Welcome to KodeKloud!
          This is Ansible Lab by victor bourman.
          This content was added using Ansible blockinfile module.
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
#ansible-playbook -i /home/thor/playbooks/inventory /home/thor/playbooks/index2.yml
#ansible-playbook --check -i /home/thor/playbooks/inventory /home/thor/playbooks/index2.yml
#ssh root@172.20.1.100
#cat /var/www/html/index.html
#Adding a image

