---
- name: Add content to index.html on web1 node
  hosts: web1
  become: yes
  tasks:
    - name: Create the index.html file
      file:
        path: /var/www/html/index.html
        state: touch

    - name: Add content to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "This line was added using Ansible lineinfile module!"
#ansible-playbook -i /home/thor/playbooks/inventory /home/thor/playbooks/index1.yml
