---
- name: Create a blank file with specific permissions
  hosts: web1
  become: yes
  tasks:
    - name: Create the blank file
      file:
        path: /opt/data/perm.txt
        state: touch
        mode: "0640"
#ansible-playbook -i /home/thor/playbooks/inventory /home/thor/playbooks/perm.yml
